services:
  - type: web
    name: wasiseguro
    runtime: image
    repo: https://github.com/Grupo03ArquiWeb/Grupo3Arquiweb
    plan: free
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - wasiseguro/**
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: wasiseguro-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: wasiseguro-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: wasiseguro-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: SERVER_PORT
        value: 8080

databases:
  - name: wasiseguro-db
    databaseName: bdwasiseguro
    user: wasiseguro_user
    plan: free