spring.application.name=wasiseguro
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8k8qqv7f7vs73c34eq0-a.oregon-postgres.render.com:5432/bdwasiseguro_98v8
spring.datasource.username=wasiseguro_user
spring.datasource.password=VZfiMv8fdO6v8FV8RNAKRYXLh13Yp73W
jwt.secret=M1Hq3NAKAWlgSsxdBki0ehOuIA6uaknhKrVIkzGmkANMKSBG4FNvWoQU6s7lohGjhd3UsYhoKxgMQP3UTy7brukKmArx3QUJrN5nspR7_BI4VItChBjPeQy2dV0OczU47Jbfi4cth145LTTOqsth-mZ87nK7zrJYXvCu7xa2Po1YhHO6wchpuA
