spring.application.name=wasiseguro
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d7t6ktd0lvsc73cgulpg-a.oregon-postgres.render.com:5432/bdwasiseguro
spring.datasource.username=wasiseguro_user
spring.datasource.password=74Vm9uJjmWj5wL49JL0JGxjfiWeNe3J8
jwt.secret=M1Hq3NAKAWlgSsxdBki0ehOuIA6uaknhKrVIkzGmkANMKSBG4FNvWoQU6s7lohGjhd3UsYhoKxgMQP3UTy7brukKmArx3QUJrN5nspR7_BI4VItChBjPeQy2dV0OczU47Jbfi4cth145LTTOqsth-mZ87nK7zrJYXvCu7xa2Po1YhHO6wchpuA
#jwt.secret=M1Hq3NAKAWlgSsxdBki0ehOuIA6uaknhKrVIkzGmkANMKSBG4FNvWoQU6s7lohGjhd3UsYhoKxgMQP3UTy7brukKmArx3QUJrN5nspR7_BI4VItChBjPeQy2dV0OczU47Jbfi4cth145LTTOqsth-mZ87nK7zrJYXvCu7xa2Po1YhHO6wchpuA
