spring.application.name=wasiseguro
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# Render te da DATABASE_URL, no SPRING_DATASOURCE_URL
# La variable se llama DATABASE_URL
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/bdwasiseguro}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:root}

jwt.secret=${JWT_SECRET:token123}